<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SW" nsURI="https://www.w3.org/2001/sw/" nsPrefix="sw">
  <eClassifiers xsi:type="ecore:EClass" name="RDFDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sparql" ordered="false"
        upperBound="-1" eType="#//SPARQL/SparqlQuery" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owlDatatypeProperty" ordered="false"
        upperBound="-1" eType="#//OWL/DatatypeProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owlObjectProperty" ordered="false"
        upperBound="-1" eType="#//OWL/ObjectProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owlOntology" ordered="false"
        upperBound="-1" eType="#//OWL/Ontology" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owlClass" ordered="false"
        upperBound="-1" eType="#//OWL/OWLClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owlNamedIndividual" upperBound="-1"
        eType="#//OWL/NamedIndividual" containment="true"/>
  </eClassifiers>
  <eSubpackages name="RDF" nsURI="http://www.w3.org/1999/02/22-rdf-syntax-ns#" nsPrefix="RDF">
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//RDFS/Resource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="domain" eType="#//RDFS/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//RDFS/Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Statement" eSuperTypes="#//RDFS/Resource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subject" eType="#//RDFS/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//RDFS/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="#//RDFS/Resource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bag" eSuperTypes="#//RDFS/Container"/>
    <eClassifiers xsi:type="ecore:EClass" name="Seq" eSuperTypes="#//RDFS/Container"/>
    <eClassifiers xsi:type="ecore:EClass" name="Alt" eSuperTypes="#//RDFS/Container"/>
    <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//RDFS/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompoundLiteral" eSuperTypes="#//RDFS/Class"/>
  </eSubpackages>
  <eSubpackages name="RDFS" nsURI="https://www.w3.org/2000/01/rdf-schema#" nsPrefix="RDFS">
    <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//RDFS/Class"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//RDFS/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="Resource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//RDFS/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//RDFS/Literal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//RDFS/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="seeAlso" eType="#//RDFS/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isDefinedBy" eType="#//RDFS/Resource"
          derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//RDFS/Resource"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="about" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//RDFS/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//RDFS/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ContainerMembershipProperty" eSuperTypes="#//RDF/Property"/>
  </eSubpackages>
  <eSubpackages name="OWL" nsURI="https://www.w3.org/2002/07/owl#" nsPrefix="OWL">
    <eClassifiers xsi:type="ecore:EClass" name="OWLClass" eSuperTypes="#//RDFS/Class">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owlRestriction" upperBound="-1"
          eType="#//OWL/Restriction" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subClassOf" upperBound="-1"
          eType="#//OWL/OWLClass" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ontology" eSuperTypes="#//RDFS/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyProperty" eSuperTypes="#//RDF/Property"/>
    <eClassifiers xsi:type="ecore:EClass" name="DatatypeProperty" eSuperTypes="#//RDF/Property"/>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectProperty" eSuperTypes="#//RDF/Property"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamedIndividual" eSuperTypes="#//OWL/Thing"/>
    <eClassifiers xsi:type="ecore:EClass" name="Restriction" eSuperTypes="#//OWL/OWLClass">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allValuesFrom" eType="#//RDFS/Class"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onProperty" eType="#//RDF/Property"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Thing" abstract="true" eSuperTypes="#//OWL/OWLClass"/>
  </eSubpackages>
  <eSubpackages name="SPARQL" nsURI="https://www.w3.org/TR/sparql11-query/" nsPrefix="sparql">
    <eClassifiers xsi:type="ecore:EClass" name="Select">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
          eType="#//SPARQL/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="where" lowerBound="1"
          eType="#//SPARQL/Where"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Where">
      <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" lowerBound="1"
          upperBound="-1" eType="#//SPARQL/TriplePattern" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TriplePattern">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicate" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Prefix">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SparqlQuery">
      <eStructuralFeatures xsi:type="ecore:EReference" name="prefix" ordered="false"
          upperBound="-1" eType="#//SPARQL/Prefix" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="select" ordered="false"
          lowerBound="1" eType="#//SPARQL/Select"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
